[project]
name = "ldm"
description = "Latent Diffusion Model"
version = "0.0"
authors = [
]
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["ldm", "ldm.models", "ldm.models.diffusion"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
